### ISSUE TITLE
Criar livro

### ISSUE THREAD

**Issue by s-rafaeldias** [s-rafaeldias/qs-react#8]
Criar um novo livro vinculado a uma estante virtual. O livro possui os seguintes campos:
 + código: (CHAVE) XXXXX (X É ALGARISMOS DE 0 A 9)
 + título: 20 CARACTERES (NÃO PODE HAVER ESPAÇO EM BRANCO DUPLICADO) 
 + nome do autor: 40 CARACTERES
 + data de publicação: DD/MM/AA (DD É VALOR ENTRE 00 E 31, MM ENTRE 01 E 12, AA ENTRE 00 E 99)
 + gênero literário: EPOPEIA, NOVELA, CONTO, ENSAIO, ROMANCE

**Comment by RafaelDiasSilveira** [comment]
Falta validação de dados do form
